# Generated by Django 4.2.5 on 2023-09-06 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2023, 9, 6, 13, 1, 27, 610002))),
                ('product_img', models.FileField(upload_to='')),
            ],
        ),
    ]
