# Generated by Django 4.2.1 on 2023-09-07 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='General', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.FileField(default=None, max_length=255, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 9, 7, 5, 47, 4, 394630, tzinfo=datetime.timezone.utc)),
        ),
    ]
