# Generated by Django 4.2.1 on 2023-09-07 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category_alter_product_product_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 9, 7, 5, 47, 41, 403436, tzinfo=datetime.timezone.utc)),
        ),
    ]
